build/pupmod-openldap.spec
manifests/server/conf.pp
manifests/slapo/ppolicy.pp
spec/classes/server/conf_spec.rb
spec/classes/slapo/ppolicy_spec.rb
templates/etc/openldap/default.ldif.erb

- The Password Policy overlay was getting loaded into the default.ldif
even if you didn't want to use it. This has been fixed.
- Made the password policy overlay align with the latest SIMP build of
the plugin.
- This means that you *must* have version
simp-ppolicy-check-password-2.4.39-0 or later available to the system
being configured.
SIMP-315 #close #comment Be careful to update the Changelog to reflect that users need simp-ppolicy-check-password-2.4.39-0
Change-Id: Ic89bd343b300ae29bfefbab5b297664dd5a282ea

(SIMP-315) Update to work with the new PW Overlay

---

build/pupmod-openldap.spec
templates/etc/openldap/default.ldif.erb

The value of '0' for pwdGraceAuthNLimit did not allow any password
changes once the user's account had expired.
This was changed to '-1' to (usually) allow for unlimited numbers of
password retries as this is generally in line with the core operating
system.
SIMP-609 #close

(SIMP-609) Update pwdGraceAuthNLimit to -1

---

build/pupmod-openldap.spec
manifests/init.pp
manifests/pam.pp
manifests/params.pp
spec/classes/pam_spec.rb

EL7 does not currently play well with nscd and needs to be moved to sssd
by default.
This change ensures that this happens properly.
This probably needs to be combined with the work in the 'simp' module in
the future.
SIMP-645 #close
SIMP-631 #comment Update for OpenLDAP defaults

(SIMP-645) Update to handle default sssd in 7

---

CHANGELOG
manifests/pam.pp
metadata.json

Ruby-ldap is not needed in this module.
SIMP-1241 #close
SIMP-1240 #comment remove ruby-ldap from openldap

(SIMP-1241) Remove ensure of ruby-ldap

---

CHANGELOG
metadata.json
spec/classes/client_spec.rb
templates/etc/openldap/ldap.conf.erb

- Fixed bug in which multiple URIs in ldap hiera were not written into
ldap.conf.
- Fixed bug whereby DEREF configuration value in ldap.conf was not
populated correctly.
SIMP-1571 #close

(SIMP-1571) Use hiera multiple ldap URIs

---

CHANGELOG
manifests/slapo/ppolicy.pp
metadata.json

Reset max_consecutive_per_class in openldap::slapo::ppolicy to 3
SIMP-2118 #close
Change-Id: I2375564118bc4f503a2c5e4cdbb4298a967cde90

(SIMP-2118) Reset max_consecutive_per_class to 3

---

CHANGELOG
manifests/slapo/ppolicy.pp
metadata.json

Reset max_consecutive_per_class in openldap::slapo::ppolicy to 3
SIMP-2118 #close
Change-Id: I1c11e03ae750a1a3d8643b548520ff97885333f2

(SIMP-2118) Reset max_consecutive_per_class

---

metadata.json
spec/classes/client_spec.rb
spec/fixtures/hieradata/default.yaml

This commit also updates the requirements in the metadata.json to
require Puppet >= 4.6
SIMP-2711 #close

(SIMP-2711) Fix spec tests

---

CHANGELOG
manifests/server/conf.pp
metadata.json

The default should be 1000 instead of 100 per the man page
SIMP-2816 #close

(SIMP-2816) Fix conn_max_pending_auth parameter

---

CHANGELOG
manifests/server/conf.pp
spec/acceptance/suites/default/templates/server_hieradata.yaml.erb
spec/acceptance/suites/default/templates/server_hieradata_tls.yaml.erb
spec/fixtures/hieradata/default.yaml

- server::conf::rootpw default no longer references simp_options,
it defaults to undef.
SIMP-2833 #close

(SIMP-2833) Changed server::conf::rootpw default

---

.gitlab-ci.yml
spec/classes/client_spec.rb

* the spec tests for simp_openldap will break if the change to
simplib::ldap::domain_to_dn in SIMP-2994 are merged in. This fixes
those tests
SIMP-2994 #comment

(SIMP-2994) Change case of DC= in ldap dn

---

CHANGELOG
manifests/client.pp
metadata.json
spec/classes/client_spec.rb
templates/etc/openldap/ldap.conf.erb

The client LDAP libraries are broken in EL6 such that, if any 128 bit
ciphers are present in the cipher string, it will fall back to SSF=128
for connecting to an LDAP server.
This is unacceptable to the SIMP default configuration (SSF=256).
Also, fixed a bug in a template with regards to variables with prefaced
underscores.
SIMP-2992 #close Update for OpenLDAP Client

(SIMP-2992) Work around for broken LDAP libs

---

spec/acceptance/nodesets/default.yml
spec/acceptance/suites/default/00_default_spec.rb
spec/acceptance/suites/default/01_simp_ppolicy_check_password_spec.rb

We publish a simp-ppolicy-check-password RPM and we need to be sure
that it's still functional as time moves forward.
The basic tests *should* do this, but they don't always update
openldap to the latest version.
SIMP-3152 #close

(SIMP-3152) Added a test to check published RPM

---

CHANGELOG
manifests/server/conf/default_ldif.pp
metadata.json
spec/classes/server/conf_spec.rb
templates/etc/openldap/default.ldif.erb

Allow users to set the 'users' and 'administrators' GID values in the
'default.ldif' file.
These were *not* exposed at a higher level to prevent needing to make
breaking changes in the near future and given that none of the other
settings were exposed at that level.
If this is needed, we will need to create another change in the future.
SIMP-4131 #close
SIMP-4132 #close

(SIMP-3894) Allow custom GIDs in default.ldif

---

.gitlab-ci.yml
CHANGELOG
manifests/init.pp
metadata.json

- Updated $app_pki_external_source to accept any string. This matches the
functionality of pki::copy.
SIMP-5296 #comment Updated simp_openldap
SIMP-5300 #close

(SIMP-5300) updated $app_pki_external_source type

---

CHANGELOG
manifests/server/syncrepl.pp
metadata.json

- Use simplib::validate_re_array in lieu of deprecated Puppet 3 validate_re_array
- Use Puppet Integer() in lieu of simplib's deprecated Puppet 3 to_integer
SIMP-6118 #close

(SIMP-6118)Use namespaced simplib::validate_re_array

---

.gitlab-ci.yml
.travis.yml
Gemfile

This patch updates the puppet and ruby versions in the Gitlab CI
pipeline to reflect the latest PE LTS releases.  Most notably, it adds
specific tests for PE2019.8 LTS.
SIMP-7929 #close
[SIMP-7848] #comment Add PE2019.8 to GL CI in pupmod-simp-simp_openldap
[SIMP-7855] #comment Update GL CI to PE2018.1.15 in pupmod-simp-simp_openldap
[SIMP-7848]: https://simp-project.atlassian.net/browse/SIMP-7848
[SIMP-7855]: https://simp-project.atlassian.net/browse/SIMP-7855

(SIMP-7848) Add PE2019.8 to pupmod-simp-simp_openldap GL pipeline

---

.gitattributes
.gitignore
.gitlab-ci.yml
.pmtignore
.puppet-lint.rc
Gemfile
spec/classes/client_spec.rb

This patch baselines the latest standardized assets for Puppet modules.
SIMP-9087 #close
[SIMP-8958] #comment Standardized assets in pupmod-simp-simp_openldap
[SIMP-8839] #comment Removed EL6 from supported OSes in pupmod-simp-simp_openldap
[SIMP-8489] #comment Updated pupmod-simp-simp_openldap GLCI pipeline to Puppet 6.18
[SIMP-8923] #comment Renamed 'sanity' to 'releng' in pupmod-simp-simp_openldap
[SIMP-8984] #comment Updated pupmod-simp-simp_openldap to new GLCI conventions
[SIMP-8958]: https://simp-project.atlassian.net/browse/SIMP-8958
[SIMP-8839]: https://simp-project.atlassian.net/browse/SIMP-8839
[SIMP-8489]: https://simp-project.atlassian.net/browse/SIMP-8489
[SIMP-8923]: https://simp-project.atlassian.net/browse/SIMP-8923
[SIMP-8984]: …

(SIMP-8958) Standardize assets in pupmod-simp-simp_openldap

---

.github/workflows/pr_glci.yml
.github/workflows/pr_glci_manual.yml
.github/workflows/pr_tests.yml
.gitlab-ci.yml

This patch updates the standardized GitHub Actions that trigger GLCI
pipelines:
- Still preemptively cancels existing GLCI pipelines for the same
branch, EXCEPT when a pipeline is for the same commit hashref.
- Refactored common GLCI logic into new composite run steps actions:
- [github-action-gitlab-ci-pipeline-trigger@v1][0]
- [github-action-gitlab-ci-syntax-check@v1][1]
This patch also enforces the standardized asset baseline using
simp/puppetsync, and may apply other updates to ensure conformity.
CI: SKIP MATRIX
[SIMP-9342] #close
[SIMP-9266] #comment Standardized GHA + assets in pupmod-simp-simp_openldap
[SIMP-9279] #comment `.fixtures.yml` triggers GLCI acc for pupmod-simp-simp_openldap
[0]: https://github.com/simp/github-action-gitlab-ci-pipeline-trigger
[1]: …

(SIMP-9266) Improve GHA GCLI trigger in pupmod-simp-simp_openldap

---

manifests/init.pp
manifests/server.pp

Second attempt at the fix. Although the original fix worked for the
acceptance tests in this module, it did not work in simp-core's
default acceptance test. This means the original solution was
too heavily tied to nondeterministic compiler behavior.
SIMP-9380 #close

(SIMP-9380) simp_openldap client pki::copy fails

---

spec/acceptance/nodesets/default.yml
spec/acceptance/nodesets/oel.yml
spec/acceptance/suites/default/00_default_server_spec.rb
spec/acceptance/suites/multi_tier/00_default_spec.rb

- update the EL8 nodes in the acceptance tests
to run with generic/centos8 to make sure they using
CentOS 8.4
- update oel7 box to generic from onyxpoint in nodesets
SIMP-10204 #comment update simp_openldap
SIMP-10244 #close

(SIMP-10204) Ensure testing with CentOS 8.4

---

.github/workflows/pr_tests.yml
.gitlab-ci.yml
Gemfile
spec/acceptance/nodesets/default.yml
spec/acceptance/nodesets/oel.yml
spec/acceptance/nodesets/rhel7.yml

This patch moves puppet 6 refs to 7, puppet 7 refs to 8. Then we manually
update all spec nodesets to point to sicura oel boxes and comment out all 
pup8 tests.
The patch enforces a standardized asset baseline using simp/puppetsync,
and may also apply other updates to ensure conformity.

Removes puppet 6 from .gitlab-ci.yml

---

.github/workflows/pr_tests.yml
.puppet-lint.rc
CHANGELOG
Gemfile
manifests/client.pp
manifests/init.pp
manifests/server.pp
manifests/server/fix_bad_upgrade.pp
manifests/server/install.pp
metadata.json
spec/classes/client_spec.rb

This patch adds support for RockyLinux 8
The patch enforces a standardized asset baseline using simp/puppetsync,
and may also apply other updates to ensure conformity.

Add RockyLinux 8 support

---

CHANGELOG
lib/facter/openldap_arch.rb
metadata.json

Replace call to `FileTest.exists?` with `FileTest.exist?` for compatibility with Ruby 3
Closes #127

Remove use of FileTest.exists?

---

.fixtures.yml
CHANGELOG
metadata.json
spec/spec_helper.rb

Update module dependencies to support simp-iptables 7.x.

[puppetsync] Support simp-iptables 7.x
